name: Backup to Dropbox

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zip and curl
        run: sudo apt-get install -y zip curl

      - name: Create backup archive
        run: |
          TIMESTAMP=$(date +"%Y-%m-%dT%H-%M-%S")
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
          COMMIT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          ZIP_NAME="backup-${BRANCH_NAME}-${COMMIT_SHA}-${TIMESTAMP}.zip"
          zip -r "$ZIP_NAME" . -x ".git/*"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload to Dropbox
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        run: |
          echo "Uploading $ZIP_NAME to Dropbox..."
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer $DROPBOX_ACCESS_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\": \"/github-backups/$ZIP_NAME\",\"mode\": \"add\",\"autorename\": true,\"mute\": false}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @"$ZIP_NAME"

      - name: Done
        run: echo "✅ Backup uploaded to Dropbox successfully!"
